name: GitHub Actions Secret Example

on:
  push:
    Branches: [main]
jobs:
  secrets-in-github-actions:
    runs-on: windows-latest
    
    
    # The Secret Actions Github example has three steps 
    steps :
      # Show how to print unmasked Github secrets to the console 
      - name: Step 1 - Echo out a Github Actions Secret to the logs
    run: |
        echo "The GitHub Action Secret will be masked: "
        echo ${{ secrets.POTATO }}
        echo "Trick to echo GitHub Actions Secret: "
        echo ${{ secrets.POTATO }} | sed 's/ ./& /g'
